[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-bdd-orama-playground"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pytest",
    "pytest-bdd",
    "pytest-bdd-orama",
    "pyyaml",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
bdd_features_base_dir = "features"
